name: Send mail

on:
  push:
    branches:
      - "!*"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version' # Read python version from a file .python-version

      - name: Install pipenv
        run: pip install pipenv

      - name: Install requirements libs
        run: pipenv install

      - name: Send mail by send_mail.py
        env:
          GOOGLE_API_CREDENTIALS: ${{ secrets.GOOGLE_API_CREDENTIALS}}
          GOOGLE_API_MAIL_FROM: ${{ secrets.GOOGLE_API_MAIL_FROM }}
          GOOGLE_API_MAIL_TO: ${{ secrets.GOOGLE_API_MAIL_TO }}
        run: pipenv run python send_mail.py
